title: Morgan Roderick's blog
author: Morgan Roderick
safe:        false
future:      true
lsi:         false
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink:   /:year/:month/:day/:title/
exclude:     ['node_modules']
plugins:
  - jekyll-feed
jekyll_compose:
    auto_open: true
